name: waf tests
on: 
  push:
    branches:
      - main-branch
    
jobs:
  test-rules:
    name: waf tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          path: waf-simulator
      
      - name: set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.5'
      
      - name: build waf tests
        run: |
          cd waf-simulator
          go build -o ../waf-tests tests/main.go

      - name: waf simulation tests
        run: ./waf-tests
        env:
          SIGSCI_CORP: ${{ secrets.SIGSCI_CORP }}
          SIGSCI_EMAIL: ${{ secrets.SIGSCI_EMAIL }}
          SIGSCI_TOKEN: ${{ secrets.SIGSCI_TOKEN }}
